[texts]

[texts.input]
path = "texts.csv" # path to the texts file
filter = false     # if true, only texts in the filter list will be used


[texts.filters]
alphanumeric = false              # if true, only strictly alphanumeric texts will be used
case_sensitive = false            # if true, case sensitive search will be used
min_length = 0                    # minimum length of the text
max_length = 1024                 # maximum length of the text
punctuation = false               # if true, texts with punctuation will not be used
numbers = false                   # if true, texts with numbers will not be used
special_characters = false        # if true, texts with special characters will not be used
accept_special_characters = ".,-" # list of special characters to accept in the text (if special_characters is true)

[annotations]
format = "spacy" # format of the output file (jsonl, spaCy, brat, standoff)

[annotations.output]
path = "annotations.jsonl" # path to the output file

[entities]

[entities.input]
path = "entities.csv" # path to the entities file
filter = true         # if true, only entities in the filter list will be used

[entities.excludes]
# path = "excludes.csv" # path to entities to exclude from the search

[entities.filters]
alphanumeric = false             # if true, only strictly alphanumeric entities will be used
case_sensitive = false           # if true, case sensitive search will be used
min_length = 0                   # minimum length of the entity
max_length = 20                  # maximum length of the entity
punctuation = false              # if true, entities with punctuation will not be used
numbers = false                  # if true, entities with numbers will not be used
special_characters = true        # if true, entities with special characters will not be used
accept_special_characters = ".-" # list of special characters to accept in the entity (if special_characters is true)
