name: Rust Package CI

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: katyo/publish-crates@v2
        with:
            path: './quickner-cli'
            args: --no-verify
            dry-run: true
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}