name: Rust Package CI

on:
  push:
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            path: './quickner-cli'
            args: --all-targets --all-features -- -D warnings
  cargo-publish:
    runs-on: ubuntu-latest
    needs: clippy
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: katyo/publish-crates@v2
        with:
            path: './quickner-cli'
            args: --no-verify
            dry-run: true
            ignore-unpublished-changes: true
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

